// Fixed trusted sources that are automatically added to every new user during onboarding
// These are the curated media sources managed by the platform
export const FIXED_TRUSTED_SOURCES = [
  "Advanced Television",
  "Arabian Business",
  "Australian Mining",
  "Aviation Week & Space Technology",
  "Avionics News Magazine",
  "BBC",
  "Bloomberg",
  "BNamericas",
  "Breaking Defense",
  "Broadband TV News",
  "Business Insider",
  "C4ISRNet",
  "CNBC",
  "Communications Africa",
  "Convergencia Latina",
  "Cruise Industry News",
  "CSI magazine",
  "Defence Connect Australia",
  "Defense Daily",
  "Defense News",
  "Digital Ship",
  "Dow Jones",
  "Energy News Bulletin",
  "Engineering & Mining Journal",
  "Expansión",
  "Fierce Network",
  "Fierce Wireless",
  "Forbes (BRA)",
  "Forbes (MEX)",
  "GeekWire",
  "Global Mining Review",
  "GovExec",
  "Inside Telecom",
  "Jane's Defence Weekly",
  "Light Reading",
  "Mining Review Africa",
  "Revista Mineria",
  "RTL",
  "Runway Girl Network",
  "Satellite World",
  "Satellite World - SatCom",
  "SET Portal",
  "Space Intel Report",
  "Space News",
  "Telesemana",
  "Teletime",
  "The Economist",
  "The Financial Times",
  "TVBEurope",
  "UK Defense Journal",
  "Wall Street Journal",
  "Washington Post",
  "Wired"
] as const;
